# Dockerfile para el proyecto Vue.js

# Usa una imagen de Node.js para construir y servir la aplicación
FROM node:16-alpine

WORKDIR /app

# Instala las dependencias
#RUN yarn install

# Construye la aplicación
#RUN yarn build

# Expone el puerto 8080
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["yarn", "serve"]
